"""
compliance.reconcile — where the regimes disagree, and what to do about it.

These frameworks were written independently and they do not agree. The sharpest
case is log retention:

    EU AI Act Art. 19 / Art. 26(6)   keep logs for AT LEAST six months
    GDPR Art. 5(1)(e)                keep personal data NO LONGER than necessary

Both can bind the same record. The Act anticipates this — the floor applies
"unless provided otherwise in applicable Union or national law, in particular
Union law on the protection of personal data" — which resolves the legal
hierarchy without resolving the engineering question of how long to actually
keep anything.

A control set that shows only green is a sales document. This one surfaces each
conflict per data class so a deployment resolves it deliberately, and records
the reasoning where an auditor will look for it.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional

from privacy.retention import CLASSES, DAY, AI_ACT_LOG_FLOOR


@dataclass
class Conflict:
    data_class: str
    floor_days: int
    floor_source: str
    ceiling_principle: str
    configured_days: int
    resolved: bool
    guidance: str

    def to_dict(self) -> dict[str, Any]:
        return {"dataClass": self.data_class, "floorDays": self.floor_days,
                "floorSource": self.floor_source,
                "ceilingPrinciple": self.ceiling_principle,
                "configuredDays": self.configured_days,
                "resolved": self.resolved, "guidance": self.guidance}


#: Classes that plausibly constitute "logs automatically generated by the
#: system" for AI Act purposes when XCP fronts a high-risk deployment.
AI_ACT_LOG_CLASSES = ("security_audit", "call_chain")


def reconcile_retention(ai_act_applies: bool = True) -> list[Conflict]:
    """
    Every class where a retention floor and a minimisation ceiling both bite.

    `ai_act_applies` is a deliberate argument rather than an assumption: most
    deployments are not fronting a high-risk AI system, and importing a
    six-month floor you do not owe is its own compliance error — it keeps
    personal data longer than necessary, which is the GDPR breach.
    """
    floor_days = AI_ACT_LOG_FLOOR // DAY
    out: list[Conflict] = []
    for cid in AI_ACT_LOG_CLASSES:
        c = CLASSES[cid]
        configured = c.retention_days
        if not ai_act_applies:
            out.append(Conflict(
                data_class=cid, floor_days=0,
                floor_source="not applicable — no high-risk AI system declared",
                ceiling_principle="GDPR Art. 5(1)(e): no longer than necessary",
                configured_days=configured, resolved=True,
                guidance=(f"No AI Act floor applies, so {configured} days must be "
                          "justified by necessity alone. Shorten it if you cannot.")))
            continue
        meets = configured >= 184          # six calendar months, worst case
        out.append(Conflict(
            data_class=cid, floor_days=floor_days,
            floor_source="EU AI Act Art. 19 / Art. 26(6) — six calendar months",
            ceiling_principle="GDPR Art. 5(1)(e): no longer than necessary",
            configured_days=configured,
            resolved=meets,
            guidance=(
                f"{configured} days meets the six-month floor and is the "
                "shortest period that does, which is the reconciliation GDPR "
                "asks for: satisfy the floor, then stop."
                if meets else
                f"{configured} days is BELOW the floor. Six calendar months can "
                "run to 184 days, so any figure under that breaches Art. 26(6) "
                "while looking reasonable.")))
    return out


def unresolved() -> list[Conflict]:
    return [c for c in reconcile_retention() if not c.resolved]


def summary(ai_act_applies: bool = True) -> dict[str, Any]:
    conflicts = reconcile_retention(ai_act_applies)
    return {
        "aiActApplies": ai_act_applies,
        "conflicts": [c.to_dict() for c in conflicts],
        "unresolved": [c.data_class for c in conflicts if not c.resolved],
        "note": (
            "Retention floors and minimisation ceilings bind the same records. "
            "The AI Act floor applies 'unless provided otherwise in applicable "
            "Union or national law, in particular Union law on the protection "
            "of personal data'. Decide per deployment and record the reasoning; "
            "this tool surfaces the conflict, it does not resolve it for you."),
        "notLegalAdvice": True,
    }


def apply_ai_act_floor() -> dict[str, int]:
    """
    Retention overrides for a deployment that DOES front a high-risk AI system.

    Returned rather than applied globally on purpose. Most deployments are not
    high-risk, and raising everyone's retention to a floor they do not owe would
    keep personal data longer than necessary — trading an AI Act finding for a
    GDPR one. An operator opts in by declaring their situation.

        overrides = apply_ai_act_floor()
        # {"call_chain": 190, "security_audit": 190}
    """
    floor = AI_ACT_LOG_FLOOR // DAY
    return {cid: max(CLASSES[cid].retention_days, floor)
            for cid in AI_ACT_LOG_CLASSES}


__all__ = ["Conflict", "reconcile_retention", "unresolved", "summary",
           "apply_ai_act_floor", "AI_ACT_LOG_CLASSES"]
