#!/usr/bin/env python3
"""
compile-contracts.py — compile the Solidity and regenerate ABIs.

The ABIs used to be hand-maintained. That is how `SessionRegistry.abi.json` came
to declare an `addGuardian` function the contract never had: any client using it
would have encoded a call into nothing. ABIs are now generated, never edited.

    python scripts/compile-contracts.py            # uses solc on PATH
    SOLC=/path/to/solc python scripts/compile-contracts.py

solc 0.8.24 static builds: https://github.com/ethereum/solidity/releases
"""
import json, os, pathlib, shutil, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "core" / "contracts"
OUT = SRC / "build"
CONTRACTS = ["NodeRegistry.sol", "SessionRegistry.sol"]
SOLC_VERSION = "0.8.24"


def main() -> int:
    solc = os.environ.get("SOLC") or shutil.which("solc")
    if not solc:
        print("solc not found. Install 0.8.24 from\n"
              "  https://github.com/ethereum/solidity/releases/download/"
              f"v{SOLC_VERSION}/solc-static-linux\n"
              "or set SOLC=/path/to/solc", file=sys.stderr)
        return 2

    ver = subprocess.run([solc, "--version"], capture_output=True, text=True).stdout
    if SOLC_VERSION not in ver:
        print(f"warning: expected solc {SOLC_VERSION}, got: {ver.strip().splitlines()[-1]}",
              file=sys.stderr)

    OUT.mkdir(parents=True, exist_ok=True)
    args = [solc, "--optimize", "--optimize-runs", "200",
            "--combined-json", "abi,bin"] + [str(SRC / c) for c in CONTRACTS]
    r = subprocess.run(args, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stderr, file=sys.stderr)
        return 1
    if "Warning" in r.stderr:
        print(r.stderr, file=sys.stderr)

    data = json.loads(r.stdout)
    for key, c in data["contracts"].items():
        name = key.split(":")[-1]
        abi = c["abi"] if not isinstance(c["abi"], str) else json.loads(c["abi"])
        (OUT / f"{name}.json").write_text(json.dumps({
            "contractName": name,
            "_comment": ("Generated by scripts/compile-contracts.py. Do not "
                         "hand-edit."),
            "compiler": f"solc {SOLC_VERSION} --optimize --optimize-runs 200",
            "abi": abi,
            "bytecode": "0x" + c["bin"],
        }, indent=2) + "\n")
        print(f"  {name}: {len(abi)} abi entries, {len(c['bin'])//2} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
